### ISSUE TITLE
Relies On Dependency Not Specified In Package.json

### ISSUE THREAD

**Issue by bonedaddy** [verified-network/via-issuer#19]
Attempting to run `truffle compile` from a fresh clone of this repository fails with the following error 

```
Error: Cannot find module './lib/websocket'
Require stack:
- /media/solidity/DATA/Code/via-issuer/node_modules/ws/index.js
- /media/solidity/DATA/Code/via-issuer/node_modules/@trufflesuite/web3-provider-engine/subproviders/websocket.js
- /media/solidity/DATA/Code/via-issuer/node_modules/@truffle/hdwallet-provider/dist/index.js
- /media/solidity/DATA/Code/via-issuer/truffle-config.js
- /home/solidity/.npm_modules/lib/node_modules/truffle/node_modules/original-require/index.js
- /home/solidity/.npm_modules/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/media/solidity/DATA/Code/via-issuer/node_modules/ws/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/media/solidity/DATA/Code/via-issuer/node_modules/@trufflesuite/web3-provider-engine/subproviders/websocket.js:4:39)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/media/solidity/DATA/Code/via-issuer/node_modules/@truffle/hdwallet-provider/src/index.ts:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/media/solidity/DATA/Code/via-issuer/truffle-config.js:1:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Object.require (internal/modules/cjs/helpers.js:72:18)
    at Function.load (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:161:1)
    at Function.detect (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:150:1)
Truffle v5.1.51 (core: 5.1.51)
Node v12.18.2
```

Running `npm install ws` fixes the issue, and adds the dependencies to `package.json`

**Comment by kallolborah** [comment]
Done, I am closing this.
