### ISSUE TITLE
Upgrading contracts

### ISSUE THREAD

**Issue by kallolborah** [verified-network/via-issuer#38]
There is a upgrade.js in the base folder, not tested yet. Not sure if this is the right way to upgrade implementation contracts like cash and bond. We need production grade process and tools for upgrading contracts

**Comment by bonedaddy** [comment]
Links

* https://github.com/OpenZeppelin/openzeppelin-sdk/tree/master/packages/lib#readme

**Comment by bonedaddy** [comment]
# Cash.sol Errors

```
Error: Contract `Cash` is not upgrade safe

Cash.sol:62: Variable `lock` is assigned an initial value
    Move the assignment to the initializer
    https://zpl.in/upgrades/error-004

Cash.sol:42: Defining structs like `conversion` is not yet supported
    If you have manually checked for storage layout compatibility, you can skip this check with the `unsafeAllowCustomTypes` flag
    https://zpl.in/upgrades/error-007

*: Linking external libraries like `stringutils` is not yet supported
    Use libraries with internal functions only, or skip this check with the `unsafeAllowLinkedLibraries` flag 
    if you have manually checked that the libraries are upgrade safe
    https://zpl.in/upgrades/error-006

erc/ERC20.sol:18: Variable `decimals` is assigned an initial value
    Move the assignment to the initializer
    https://zpl.in/upgrades/error-004
    at Object.assertUpgradeSafe (/media/solidity/DATA/Code/via-issuer/node_modules/@openzeppelin/upgrades-core/src/validate.ts:201:11)
    at deployProxy (/media/solidity/DATA/Code/via-issuer/node_modules/@openzeppelin/truffle-upgrades/src/deploy-proxy.ts:49:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at module.exports (/media/solidity/DATA/Code/via-issuer/migrations/2_deploy_contracts.js:27:5)
    at Migration._deploy (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:73:1)
    at Migration._load (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:269:1)
    at /home/solidity/.npm_modules/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:231:1
Truffle v5.1.51 (core: 5.1.51)
Node v12.18.2
```

**Comment by kallolborah** [comment]
@bonedaddy i have made the initialiser related changes and pushed them to the ‘oracle’ branch. This branch also has all my commits for cash which is now functionally correct. I am working on bond. You may wish to merge the oracle branch but the branch is several commits ahead of master and a few commits behind - primarily, the pausable related changes

**Comment by bonedaddy** [comment]
Currently running into an issue where I'm able to deploy the contracts to rinkeby, however nothing seems to happen when sending eth to the cash contract. I suspect there is some sort of linking/forwarding/calling issue between the contract created by the factory, and the proxies deployed.

**Comment by bonedaddy** [comment]
I think I've spotted the problem, it appears that delegatecall is forwarding calls to the all `0x0` address.

**Comment by kallolborah** [comment]
@bonedaddy i tried to look up the upgrade specific code you have added but couldn’t find it. Which files have you edited in the upgrade branch ? And call forwarding is working well till now - did you make any change In the upgrade branch ?

**Comment by bonedaddy** [comment]
So I didnt change the contract code because as far as I can tell from the documentation it doesn't need to be changed. What I did change was the contract migrations [here](https://github.com/verified-network/via-issuer/blob/upgrade/migrations/2_deploy_contracts.js)

**Comment by kallolborah** [comment]
@bonedaddy i had put some code here https://github.com/verified-network/via-issuer/blob/upgrade/upgrade.js - didn’t test it though. Can you check ? I looked at your code and didn’t understand it fully

**Comment by bonedaddy** [comment]
> @bonedaddy i had put some code here https://github.com/verified-network/via-issuer/blob/upgrade/upgrade.js - didn’t test it though. Can you check ? I looked at your code and didn’t understand it fully

The code here is for the deprecated openzepplin upgrades library which has been replaced with the openzeppelin upgrades plugin which is what I'm using in the migration files.

**Comment by bonedaddy** [comment]
Did some digging and it appears that the minimal proxy isn't compatible with the new openzeppelin upgrades plugin. I did find [this](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2371/files) which appears to be a possible alternative to the minimal proxy

**Comment by kallolborah** [comment]
@bonedaddy I have created a new branch 'upgradeable' where I have committed the oracle branch updated with changes for upgradeable proxies. This includes :
1. changing openzeppelin libraries 
2. fixing compiler version at 0.6.12, for which I also updated provable_API.sol for compatibility
3. adding receive / override / virtual keyword related changes

We have been using Minimal proxies so far which is a inexpensive way to create multiple proxies of the same contract (cash/bond). However, the ProxyFactory for creating minimal proxies can not deploy these proxies as upgradeable proxies.

Now, before moving away from Minimal proxies, we ought to think what benefit we will get from Upgradeable proxies. In our deployment, we may have upto 20 cash tokens, but hundreds of bond tokens. If we do need to change functionality of cash, bond, and token, how can we recover data from minimal proxies ?

On the other hand, the challenge with Upgradeable proxies is that their usage is shown from javascript (truffle migrations) and not from solidity. I can see that it is entirely possible to pass the parameters required in the initialize() of cash and bond from migrations script itself but what do we do about the initialize() in token.sol ? That is actually called from the createToken() in factory.sol which is invoked by the bond contract when a user wants to create a bond token.

I am going through this article https://blog.openzeppelin.com/the-state-of-smart-contract-upgrades/ which shows some solidity code for deploy proxies which we may perhaps be able to use in factory.sol's createIssuer() and createToken() functions. If we can do that, we need not modify the migration script at all.

**Comment by kallolborah** [comment]
@bonedaddy saw this only now https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/lib/contracts/upgradeability/ProxyFactory.sol - this has a deployproxy() that we can use to upgrade the proxies, I think. Also saw this on a thread in OZ forum where I was posting the question. If this works, then we can simply ignore upgrades plugins and use our oracle branch code and just add a upgrade function that we can call from migrations.

**Comment by bonedaddy** [comment]
> @bonedaddy saw this only now https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/lib/contracts/upgradeability/ProxyFactory.sol - this has a deployproxy() that we can use to upgrade the proxies, I think. Also saw this on a thread in OZ forum where I was posting the question. If this works, then we can simply ignore upgrades plugins and use our oracle branch code and just add a upgrade function that we can call from migrations.

We can definitely do this, but but openzeppelin-sdk is the deprecated library and no longer maintained.

**Comment by kallolborah** [comment]
@bonedaddy please see https://forum.openzeppelin.com/t/creating-upgradeable-contracts-from-solidity-is-it-mandatory-to-use-app-sol/3594/4

This is a fairly recent thread, I think. This is what I saw when I was posting the question in the forum. OZ sdk is not actively developed but it should work. OZ is in the process of porting proxyfactory to OZ contracts which is the new name of the SDK. 

While we wait for OZ response to our posts, let me try this in the oracle branch today and you can check if it works.

**Comment by kallolborah** [comment]
@bonedaddy I could deploy the upgradeable proxies using ProxyFactory - please check out the updated oracle branch. I am not sure how to upgrade them - do we call deploy() again in ProxyFactory with the same data parameters but with a new implementation address ? Can you check ?

I am also facing another issue after deploying upgradeable proxies using ProxyFactory. My tests are failing with a Error: Returned error: VM Exception while processing transaction: revert Cannot call fallback function from the proxy admin

It is coming from this line which was working fine with minimal proxies earlier.
console.log("Account Via-USD cash token balance before sending ether:", await web3.utils.hexToNumberString(await web3.utils.toHex(await viausdCash.balanceOf(accounts[0]))));

I have posted this also in OZ forum.

**Comment by bonedaddy** [comment]
I took a look at the code, and I don't think the functions need to have "override" added, I Wonder if that might be part of the problem. [I got a response to my oz forum thread](https://forum.openzeppelin.com/t/proxy-contracts-forwarding-calls-to-zero-address-despite-initialization/4818/2?u=bonedaddy) and it looks like we can't use minimal proxies ontop of the upgradeable proxies.

I put together a basic on-chain upgradeable proxy factory using the newer openzeppelin contracts.

[This is the onchain factory](https://github.com/bonedaddy/bdsm/blob/master/contracts/TestProxyFactory.sol) which [deploys this example contract](https://github.com/bonedaddy/bdsm/blob/master/contracts/StructAssignTest.sol) leveraging [this proxy factory that deploys upgradeable proxies](https://github.com/bonedaddy/bdsm/blob/master/contracts/ProxyFactory.sol) by using [this proxy contract that wraps the transparent upgradeable proxy](https://github.com/bonedaddy/bdsm/blob/master/contracts/proxy/Proxies.sol). This set of contracts is the equivalent of an on-chain `deployProxy`.

**Comment by kallolborah** [comment]
@bonedaddy that could be it, but how do we use a separate account to deploy proxies and a separate account to test ?

**Comment by kallolborah** [comment]
@bonedaddy the OZ forum response to my post had this link for a simple wrapper that uses the upgradeable proxy https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2371 - are you also doing what this does ?

**Comment by kallolborah** [comment]
@bonedaddy got this to my post on oz forum today https://forum.openzeppelin.com/t/programmatically-deploying-upgradeable-proxies/4834/5

Perhaps you can respond after you try out the suggestions ?

**Comment by bonedaddy** [comment]
> @bonedaddy got this to my post on oz forum today https://forum.openzeppelin.com/t/programmatically-deploying-upgradeable-proxies/4834/5
> 
> Perhaps you can respond after you try out the suggestions ?

Yes I replied with a follow up question, I think the issue is happening because `deployProxy` creates the network file, but as I believe we are unable to use that with the proxy factory, we will have to create it manually.
